### ISSUE TITLE
OutOfMemory

### ISSUE THREAD

**Issue by denyska** [GoogleCloudPlatform/stackdriver-zipkin#29]
We noticed good number of Out Of Memory exceptions: 1GB of heap usually lasts 18 day (or about 60M spans).

![screen shot 2017-03-09 at 11 38 35 am](https://cloud.githubusercontent.com/assets/1242726/23774727/f651f898-04d9-11e7-9f23-002e0e3f6dab.png)

![render](https://cloud.githubusercontent.com/assets/1242726/23774755/186e6560-04da-11e7-819a-9cf613727188.png)

2017-03-04 08:20:39.318  WARN 6 --- [ZipkinStackdriverStorage-1] zipkin.server.ZipkinHttpCollector        : Cannot store spans [d01bbdc1e6bc764a.dba1b073167c995b<:d01bbdc1e6bc764a] d
ue to StatusRuntimeException(UNAVAILABLE: 502:Bad Gateway)

io.grpc.StatusRuntimeException: UNAVAILABLE: 502:Bad Gateway
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:230) ~[grpc-stub-1.0.1.jar!/:1.0.1]
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:211) ~[grpc-stub-1.0.1.jar!/:1.0.1]
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:144) ~[grpc-stub-1.0.1.jar!/:1.0.1]
        at com.google.devtools.cloudtrace.v1.TraceServiceGrpc$TraceServiceBlockingStub.patchTraces(TraceServiceGrpc.java:278) ~[grpc-google-devtools-cloudtrace-v1-0.1.0.jar!/:na]
        at com.google.cloud.trace.grpc.v1.GrpcTraceConsumer.receive(GrpcTraceConsumer.java:58) ~[grpc-consumer-0.3.0.jar!/:na]
        at com.google.cloud.trace.zipkin.StackdriverSpanConsumer.accept(StackdriverSpanConsumer.java:45) ~[storage-0.2.0.jar!/:na]
        at zipkin.storage.InternalBlockingToAsyncSpanConsumerAdapter$1.complete(InternalBlockingToAsyncSpanConsumerAdapter.java:34) ~[zipkin-1.18.0.jar!/:na]
        at zipkin.storage.InternalBlockingToAsyncSpanConsumerAdapter$1.complete(InternalBlockingToAsyncSpanConsumerAdapter.java:32) ~[zipkin-1.18.0.jar!/:na]
        at zipkin.storage.InternalCallbackRunnable.run(InternalCallbackRunnable.java:29) ~[zipkin-1.18.0.jar!/:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]

2017-03-04 08:21:49.998  WARN 6 --- [ZipkinStackdriverStorage-1] zipkin.server.ZipkinHttpCollector        : Cannot store spans [80ac8287579346f2.533e34e880b52a36<:80ac8287579346f2, 80ac8287579346f2.80ac8287579346f2<:80ac8287579346f2] due to RuntimeException(java.lang.OutOfMemoryError: Java heap space)

java.lang.RuntimeException: java.lang.OutOfMemoryError: Java heap space
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:147) ~[grpc-stub-1.0.1.jar!/:1.0.1]
        at com.google.devtools.cloudtrace.v1.TraceServiceGrpc$TraceServiceBlockingStub.patchTraces(TraceServiceGrpc.java:278) ~[grpc-google-devtools-cloudtrace-v1-0.1.0.jar!/:na]
        at com.google.cloud.trace.grpc.v1.GrpcTraceConsumer.receive(GrpcTraceConsumer.java:58) ~[grpc-consumer-0.3.0.jar!/:na]
        at com.google.cloud.trace.zipkin.StackdriverSpanConsumer.accept(StackdriverSpanConsumer.java:45) ~[storage-0.2.0.jar!/:na]
        at zipkin.storage.InternalBlockingToAsyncSpanConsumerAdapter$1.complete(InternalBlockingToAsyncSpanConsumerAdapter.java:34) ~[zipkin-1.18.0.jar!/:na]
        at zipkin.storage.InternalBlockingToAsyncSpanConsumerAdapter$1.complete(InternalBlockingToAsyncSpanConsumerAdapter.java:32) ~[zipkin-1.18.0.jar!/:na]
        at zipkin.storage.InternalCallbackRunnable.run(InternalCallbackRunnable.java:29) ~[zipkin-1.18.0.jar!/:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
Caused by: java.lang.OutOfMemoryError: Java heap space

**Comment by adriancole** [comment]
Fascinating that metrics was behind this. Almost blog worthy!

**Comment by denyska** [comment]
Metrics were just icing of the pie ;)

**Comment by denyska** [comment]
@kevinmdavis  @adriancole  please review once you get chance
https://github.com/GoogleCloudPlatform/stackdriver-zipkin/pull/30
https://github.com/GoogleCloudPlatform/stackdriver-zipkin/pull/31

**Comment by kevinmdavis** [comment]
Closing this since this was fixed in #31.
