### ISSUE TITLE
PatchTraces API failure

### ISSUE THREAD

**Issue by sribalakumar** [GoogleCloudPlatform/stackdriver-zipkin#40]
Looks like the patchTraces API is not working from 20-07-2017. 

**Trace:**

2017-07-24 10:09:42.659  WARN 7 --- [driverStorage-1] zipkin.server.ZipkinHttpCollector        : Cannot store spans [1d38d5696efc603a.1d38d5696efc603a<:1d38d5696efc603a] due to StatusRuntimeException(UNKNOWN: extracted status from HTTP :status 404

Metadata({:status=[404], content-type=[text/html; charset=UTF-8], referrer-policy=[no-referrer], content-length=[1615], date=[Mon, 24 Jul 2017 10:09:24 GMT], alt-svc=[quic=":443"; ma=2592000; v="39,38,37,36,35"]})
DATA-----------------------------
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>**The requested URL <code>/google.devtools.cloudtrace.v1.TraceService/PatchTraces</code> was not found on this server.**  <ins>That’s all we know.</ins>
)

io.grpc.StatusRuntimeException: UNKNOWN: extracted status from HTTP :status 404

Metadata({:status=[404], content-type=[text/html; charset=UTF-8], referrer-policy=[no-referrer], content-length=[1615], date=[Mon, 24 Jul 2017 10:09:24 GMT], alt-svc=[quic=":443"; ma=2592000; v="39,38,37,36,35"]})
DATA-----------------------------
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>**The requested URL <code>/google.devtools.cloudtrace.v1.TraceService/PatchTraces</code> was not found on this server.**  <ins>That’s all we know.</ins>

	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:230) ~[grpc-stub-1.0.1.jar!/:1.0.1]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:211) ~[grpc-stub-1.0.1.jar!/:1.0.1]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:144) ~[grpc-stub-1.0.1.jar!/:1.0.1]
	at com.google.devtools.cloudtrace.v1.TraceServiceGrpc$TraceServiceBlockingStub.patchTraces(TraceServiceGrpc.java:278) ~[grpc-google-devtools-cloudtrace-v1-0.1.0.jar!/:na]
	at com.google.cloud.trace.grpc.v1.GrpcTraceConsumer.receive(GrpcTraceConsumer.java:58) ~[grpc-consumer-0.3.0.jar!/:na]
	at com.google.cloud.trace.zipkin.StackdriverSpanConsumer.accept(StackdriverSpanConsumer.java:45) ~[storage-0.2.0.jar!/:na]
	at zipkin.storage.InternalBlockingToAsyncSpanConsumerAdapter$1.complete(InternalBlockingToAsyncSpanConsumerAdapter.java:34) ~[zipkin-1.18.0.jar!/:na]
	at zipkin.storage.InternalBlockingToAsyncSpanConsumerAdapter$1.complete(InternalBlockingToAsyncSpanConsumerAdapter.java:32) ~[zipkin-1.18.0.jar!/:na]
	at zipkin.storage.InternalCallbackRunnable.run(InternalCallbackRunnable.java:29) ~[zipkin-1.18.0.jar!/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]

**Comment by sribalakumar** [comment]
Looks like gRPC is not working for other client libraries too.

Message on https://status.cloud.google.com/ is : 

> Stackdriver Trace is not storing new spans from client libraries that rely on gRPC, including Go, C#, Java, Ruby, PHP and OSS Zipkin adapter. Engineering is actively working to resolve the issue.

**Comment by zavale** [comment]
@sribalakumar Having exactly the same problem. Did you get any response from Google, or found a workaround?

**Comment by mtwo** [comment]
Hey there, one of the Stackdriver PMs here. My apologies, I just saw this thread - would have like to have seen it last week.

sribalakumar's comment was correct, we suffered a major API outage last week, though it's since been resolved. Are you still experiencing any issues with the collector?

**Comment by chyamuna** [comment]
2018-01-05 12:01:56.920 WARN 5 --- [driverStorage-1] zipkin.server.ZipkinHttpCollector : Cannot store spans [347f8b93d041a9f8.53f7579c7effc142<:347f8b93d041a9f8, 347f8b93d041a9f8.347f8b93d041a9f8<:347f8b93d041a9f8, df7f143052e33242.df7f143052e33242<:df7f143052e33242] due to StatusRuntimeException(PERMISSION_DENIED: The caller does not have permission)


I am facing this problem.I have created service account and configured accordingly.still facing the issue.
